// Generated by CoffeeScript 1.4.0
(function() {
  var LINE_PREFIX, childProcess, compact, compactMap, createFilter, createGlobFilter, createRegExpFilter, flatten, glob, identity, invert, isRegExp, isString, keys, map, watch, wrap, _,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  glob = require('glob');

  watch = require('watch');

  childProcess = require('child_process');

  _ = require('underscore');

  identity = _.identity, wrap = _.wrap, map = _.map, flatten = _.flatten, compact = _.compact, isString = _.isString, keys = _.keys;

  LINE_PREFIX = "---";

  compactMap = function(arr, fn) {
    return compact(map(flatten(arr), fn));
  };

  isRegExp = function(str) {
    var first, last;
    first = str.substring(0, 1);
    last = str.substring(str.length - 1);
    return (first === last && last === '/');
  };

  createRegExpFilter = function(filter) {
    filter = filter.substring(1, filter.length - 1);
    filter = RegExp(filter);
    return function(file) {
      return filter.test(file);
    };
  };

  createGlobFilter = function(filter) {
    return function(file) {
      return __indexOf.call(glob.sync(filter), file) >= 0;
    };
  };

  createFilter = function(filter) {
    if (isRegExp(filter)) {
      return createRegExpFilter(filter);
    } else {
      return createGlobFilter(filter);
    }
  };

  invert = function(fn) {
    return function() {
      return !fn(arguments);
    };
  };

  module.exports = function(path, command, options) {
    var Reaktr, args, exclude, excluded, include, interval, longRunning, notIncluded;
    if (options == null) {
      options = {};
    }
    longRunning = options.longRunning, interval = options.interval, exclude = options.exclude, include = options.include;
    if (include != null) {
      notIncluded = invert(createFilter(include));
    }
    if (exclude != null) {
      excluded = createFilter(exclude);
    }
    args = ['-c', command];
    if (interval == null) {
      interval = 1000;
    }
    Reaktr = (function() {

      function Reaktr() {
        this.restartProcess = __bind(this.restartProcess, this);

        this.earlyProcessExit = __bind(this.earlyProcessExit, this);

        this.startProcess = __bind(this.startProcess, this);

        this.parseFiles = __bind(this.parseFiles, this);

        this.onChange = __bind(this.onChange, this);

      }

      Reaktr.prototype.start = function() {
        var after;
        this.log("");
        this.log("Observing files in `" + path + "` and running `" + command + "` on changes");
        this.log("");
        if (include != null) {
          this.log("Include files matching: " + include);
        }
        if (exclude != null) {
          this.log("Exclude files matching: " + exclude);
        }
        if (longRunning) {
          this.process = this.startProcess();
          this.startProcess = this.processRestarter(this.startProcess);
        }
        after = _.after;
        this.onChange = after(2, this.onChange);
        return watch.watchTree(path, {
          interval: interval
        }, this.onChange);
      };

      Reaktr.prototype.log = function(message) {
        return console.log("" + LINE_PREFIX + " " + message);
      };

      Reaktr.prototype.onChange = function(files) {
        var file, _i, _len;
        files = this.parseFiles(files);
        if (!files.length) {
          return;
        }
        this.log("");
        this.log("Change detected:");
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          this.log("./" + file);
        }
        this.log("");
        return this.startProcess();
      };

      Reaktr.prototype.parseFiles = function(files) {
        if (!isString(files)) {
          files = keys(files);
        }
        return compactMap([files], this.parseFile);
      };

      Reaktr.prototype.parseFile = function(file) {
        file = file.replace("" + path + "/", '') || '/';
        if (typeof notIncluded === "function" ? notIncluded(file) : void 0) {
          file = null;
        }
        if (typeof excluded === "function" ? excluded(file) : void 0) {
          file = null;
        }
        return file;
      };

      Reaktr.prototype.startProcess = function() {
        var child;
        this.log("Running `" + command + "`");
        this.log("");
        child = childProcess.spawn("sh", args, {
          stdio: 'inherit'
        });
        if (longRunning) {
          child.on('exit', this.earlyProcessExit);
        }
        return child;
      };

      Reaktr.prototype.earlyProcessExit = function(code) {
        if (code == null) {
          code = 0;
        }
        this.log("");
        this.log("PID " + this.process.pid + " exited early with " + code);
        return this.process = null;
      };

      Reaktr.prototype.processRestarter = function(startFn) {
        var _this = this;
        return function() {
          if (_this.process == null) {
            return _this.process = startFn();
          }
          _this.log("Killing process with PID " + _this.process.pid);
          _this.process.removeListener('exit', _this.earlyProcessExit);
          _this.process.on('exit', _this.restartProcess(_this.process, startFn));
          return _this.process.kill();
        };
      };

      Reaktr.prototype.restartProcess = function(oldProcess, startFn) {
        var _this = this;
        return function(code) {
          if (code == null) {
            code = 0;
          }
          _this.log("PID " + oldProcess.pid + " exited with " + code);
          _this.log("");
          return _this.process = startFn();
        };
      };

      return Reaktr;

    })();
    return new Reaktr;
  };

}).call(this);
