// Generated by CoffeeScript 1.4.0
(function() {
  var child, equal, expect, reakt, spy, watch, _, _ref;

  _ref = require('assert'), expect = _ref.ok, equal = _ref.equal;

  spy = require('bondjs');

  child = require('child_process');

  watch = require('watch');

  _ = require('underscore');

  reakt = require('./index');

  describe('reakt', function() {
    var createSubject;
    createSubject = function(args) {
      var subject;
      if (args == null) {
        args = {};
      }
      subject = reakt("/foo/bar", 'ls ..', args);
      spy(subject, 'log')["return"]();
      return subject;
    };
    beforeEach(function() {
      return this.subject = createSubject();
    });
    describe('#start', function() {
      beforeEach(function() {
        spy(watch, 'watchTree')["return"]();
        spy(_, 'after')["return"]();
        spy(this.subject, 'processRestarter')["return"]();
        spy(this.subject, 'startProcess')["return"]();
        this.expectedStartFn = this.subject.startProcess;
        return this.subject.start();
      });
      context('when in long running mode', function() {
        beforeEach(function() {
          this.subject = createSubject({
            longRunning: true
          });
          spy(this.subject, 'processRestarter')["return"]();
          spy(this.subject, 'startProcess')["return"]();
          this.expectedStartFn = this.subject.startProcess;
          return this.subject.start();
        });
        it('starts the process with #startProcess', function() {
          return expect(this.expectedStartFn.called);
        });
        return it('wraps the #startProcess method with a #processRestarter', function() {
          var actualStartFn;
          actualStartFn = this.subject.processRestarter.calledArgs[0][0];
          return equal(actualStartFn, this.expectedStartFn);
        });
      });
      context('when not in long running mode', function() {
        it('does not start the process', function() {
          return expect(!this.expectedStartFn.called);
        });
        return it('does not wrap the startProcess method', function() {
          return expect(!this.subject.processRestarter.called);
        });
      });
      it('ensures that the #onChange handler is ran after the second invocation', function() {
        var cb, times, _ref1;
        return _ref1 = _.after.calledArgs[0], times = _ref1[0], cb = _ref1[1], _ref1;
      });
      return it('sets a watcher on the provided path', function() {
        var cb, path, _ref1;
        _ref1 = watch.watchTree.calledArgs[0], path = _ref1[0], cb = _ref1[1];
        equal(path, "/foo/bar");
        return equal(cb, this.subject.onChange);
      });
    });
    describe('#onChange', function() {
      beforeEach(function() {
        this.fakeData = ['foo'];
        spy(this.subject, 'parseFiles')["return"](this.fakeData);
        return spy(this.subject, 'startProcess')["return"]();
      });
      context('with no files', function() {
        return it('returns early', function() {
          this.subject.parseFiles["return"]([]);
          this.subject.onChange(this.fakeData);
          return expect(!this.subject.startProcess.called);
        });
      });
      return context('with files', function() {
        return it('calls #runProcess', function() {
          this.subject.parseFiles["return"](['/foo']);
          this.subject.onChange(this.fakeData);
          return expect(this.subject.startProcess.called);
        });
      });
    });
    describe('#parseFiles', function() {
      context('when called with an object', function() {
        return it('converts the objects keys to a string and returns it', function() {
          var result;
          result = this.subject.parseFiles({
            'foo': 'foo',
            'bar': 'bar'
          });
          equal(result[0], 'foo');
          return equal(result[1], 'bar');
        });
      });
      return context('when called with a string', function() {
        return it('returns the original string', function() {
          var result;
          result = this.subject.parseFiles('foo');
          return equal(result[0], 'foo');
        });
      });
    });
    describe('#parseFile', function() {
      beforeEach(function() {
        return this.subject = createSubject({
          include: "(baz\/qux|lorem\/ipsum)",
          exclude: "ipsum\/lorem"
        });
      });
      it('strips the base path', function() {
        return equal(this.subject.parseFile('/foo/bar/baz/qux'), '/baz/qux');
      });
      context('if the file does not match the include pattern', function() {
        return it('returns null', function() {
          return equal(this.subject.parseFile('/foo/bar/foo/ipsum'), null);
        });
      });
      return context('if the file matches the exclude pattern', function() {
        return it('returns null', function() {
          return equal(this.subject.parseFile('/foo/bar/ipsum/lorem'), null);
        });
      });
    });
    describe('#startProcess', function() {
      return it('spawns a child process', function() {
        var args, cmd, opts, _ref1;
        spy(child, 'spawn')["return"]();
        this.subject.startProcess();
        _ref1 = child.spawn.calledArgs[0], cmd = _ref1[0], args = _ref1[1], opts = _ref1[2];
        equal(cmd, 'sh');
        equal(args[0], '-c');
        equal(args[1], 'ls ..');
        return equal(opts.stdio, 'inherit');
      });
    });
    describe('#processRestarter', function() {
      beforeEach(function() {
        this.startFnSpy = spy()["return"]('foo');
        this.result = this.subject.processRestarter(this.startFnSpy);
        this.subject.process = {
          on: spy(),
          kill: spy()
        };
        spy(this.subject, 'onProcessExit')["return"]('bar');
        return this.result();
      });
      context('with a running process', function() {
        it('registers an exit handler on the process', function() {
          var cb, event, _ref1;
          _ref1 = this.subject.process.on.calledArgs[0], event = _ref1[0], cb = _ref1[1];
          equal(event, 'exit');
          return equal(cb, 'bar');
        });
        return it('kills the process', function() {
          return expect(this.subject.process.kill.called);
        });
      });
      return context('without a process', function() {
        return it('starts the process', function() {
          this.subject.process = null;
          this.result();
          return equal(this.subject.process, 'foo');
        });
      });
    });
    return describe('#onProcessExit', function() {
      beforeEach(function() {
        this.startFnSpy = spy()["return"]('foo');
        this.result = this.subject.onProcessExit({}, this.startFnSpy);
        return this.result();
      });
      return it('starts the process', function() {
        expect(this.startFnSpy.called);
        return equal(this.subject.process, 'foo');
      });
    });
  });

}).call(this);
